# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogModificarEmpleado.ui'
#
# Created: Sun Nov  9 12:48:20 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dialogModificarEmpleado(object):
    def setupUi(self, dialogModificarEmpleado):
        dialogModificarEmpleado.setObjectName(_fromUtf8("dialogModificarEmpleado"))
        dialogModificarEmpleado.resize(800, 600)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        dialogModificarEmpleado.setPalette(palette)
        dialogModificarEmpleado.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        dialogModificarEmpleado.setAutoFillBackground(True)
        self.widgetCabecera = QtGui.QWidget(dialogModificarEmpleado)
        self.widgetCabecera.setGeometry(QtCore.QRect(0, 0, 800, 65))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widgetCabecera.setPalette(palette)
        self.widgetCabecera.setAutoFillBackground(True)
        self.widgetCabecera.setObjectName(_fromUtf8("widgetCabecera"))
        self.layoutWidget_2 = QtGui.QWidget(self.widgetCabecera)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 0, 162, 87))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.layoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.labelColMedica = QtGui.QLabel(self.layoutWidget_2)
        self.labelColMedica.setStyleSheet(_fromUtf8("font: 30pt \"Ubuntu Condensed\";\n"
"color: rgb(255, 255, 255);"))
        self.labelColMedica.setObjectName(_fromUtf8("labelColMedica"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelColMedica)
        self.labelClinicManager = QtGui.QLabel(self.layoutWidget_2)
        self.labelClinicManager.setObjectName(_fromUtf8("labelClinicManager"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelClinicManager)
        self.widgetCuerpo = QtGui.QWidget(dialogModificarEmpleado)
        self.widgetCuerpo.setGeometry(QtCore.QRect(0, 80, 800, 511))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.widgetCuerpo.setFont(font)
        self.widgetCuerpo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.widgetCuerpo.setAutoFillBackground(True)
        self.widgetCuerpo.setObjectName(_fromUtf8("widgetCuerpo"))
        self.layoutWidget_4 = QtGui.QWidget(self.widgetCuerpo)
        self.layoutWidget_4.setGeometry(QtCore.QRect(20, 40, 371, 181))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.formLayout_3 = QtGui.QFormLayout(self.layoutWidget_4)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.labelIdentificacion = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.labelIdentificacion.setFont(font)
        self.labelIdentificacion.setObjectName(_fromUtf8("labelIdentificacion"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelIdentificacion)
        self.labelNombre = QtGui.QLabel(self.layoutWidget_4)
        self.labelNombre.setObjectName(_fromUtf8("labelNombre"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelNombre)
        self.lineEditNombre = QtGui.QLineEdit(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditNombre.setFont(font)
        self.lineEditNombre.setObjectName(_fromUtf8("lineEditNombre"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditNombre)
        self.labelDireccion = QtGui.QLabel(self.layoutWidget_4)
        self.labelDireccion.setObjectName(_fromUtf8("labelDireccion"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelDireccion)
        self.lineEditDireccion = QtGui.QLineEdit(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditDireccion.setFont(font)
        self.lineEditDireccion.setObjectName(_fromUtf8("lineEditDireccion"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditDireccion)
        self.labelTelefono = QtGui.QLabel(self.layoutWidget_4)
        self.labelTelefono.setObjectName(_fromUtf8("labelTelefono"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelTelefono)
        self.lineEditTelefono = QtGui.QLineEdit(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditTelefono.setFont(font)
        self.lineEditTelefono.setObjectName(_fromUtf8("lineEditTelefono"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditTelefono)
        self.labelEmail = QtGui.QLabel(self.layoutWidget_4)
        self.labelEmail.setObjectName(_fromUtf8("labelEmail"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.labelEmail)
        self.lineEditEmail = QtGui.QLineEdit(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditEmail.setFont(font)
        self.lineEditEmail.setObjectName(_fromUtf8("lineEditEmail"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEditEmail)
        self.comboBoxIdentificacion = QtGui.QComboBox(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBoxIdentificacion.setFont(font)
        self.comboBoxIdentificacion.setObjectName(_fromUtf8("comboBoxIdentificacion"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBoxIdentificacion)
        self.labelHabilidades = QtGui.QLabel(self.widgetCuerpo)
        self.labelHabilidades.setGeometry(QtCore.QRect(20, 310, 369, 27))
        self.labelHabilidades.setObjectName(_fromUtf8("labelHabilidades"))
        self.lineEnfermera = QtGui.QFrame(self.widgetCuerpo)
        self.lineEnfermera.setGeometry(QtCore.QRect(20, 240, 371, 20))
        self.lineEnfermera.setFrameShape(QtGui.QFrame.HLine)
        self.lineEnfermera.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineEnfermera.setObjectName(_fromUtf8("lineEnfermera"))
        self.layoutWidget_5 = QtGui.QWidget(self.widgetCuerpo)
        self.layoutWidget_5.setGeometry(QtCore.QRect(420, 40, 361, 144))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.formLayout_4 = QtGui.QFormLayout(self.layoutWidget_5)
        self.formLayout_4.setMargin(0)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.labelSalario = QtGui.QLabel(self.layoutWidget_5)
        self.labelSalario.setObjectName(_fromUtf8("labelSalario"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelSalario)
        self.lineEditSalario = QtGui.QLineEdit(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditSalario.setFont(font)
        self.lineEditSalario.setObjectName(_fromUtf8("lineEditSalario"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditSalario)
        self.labelCargo = QtGui.QLabel(self.layoutWidget_5)
        self.labelCargo.setObjectName(_fromUtf8("labelCargo"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelCargo)
        self.lineEditCargo = QtGui.QLineEdit(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditCargo.setFont(font)
        self.lineEditCargo.setObjectName(_fromUtf8("lineEditCargo"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditCargo)
        self.labelCodigoArea = QtGui.QLabel(self.layoutWidget_5)
        self.labelCodigoArea.setObjectName(_fromUtf8("labelCodigoArea"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelCodigoArea)
        self.comboBoxCodigoArea = QtGui.QComboBox(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBoxCodigoArea.setFont(font)
        self.comboBoxCodigoArea.setObjectName(_fromUtf8("comboBoxCodigoArea"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboBoxCodigoArea)
        self.labelCodigoJefe = QtGui.QLabel(self.layoutWidget_5)
        self.labelCodigoJefe.setObjectName(_fromUtf8("labelCodigoJefe"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelCodigoJefe)
        self.comboBoxCodigoJefe = QtGui.QComboBox(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBoxCodigoJefe.setFont(font)
        self.comboBoxCodigoJefe.setObjectName(_fromUtf8("comboBoxCodigoJefe"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.comboBoxCodigoJefe)
        self.labelMedico = QtGui.QLabel(self.widgetCuerpo)
        self.labelMedico.setGeometry(QtCore.QRect(420, 220, 81, 31))
        self.labelMedico.setObjectName(_fromUtf8("labelMedico"))
        self.plainTextEditHabilidades = QtGui.QPlainTextEdit(self.widgetCuerpo)
        self.plainTextEditHabilidades.setGeometry(QtCore.QRect(20, 340, 371, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.plainTextEditHabilidades.setFont(font)
        self.plainTextEditHabilidades.setObjectName(_fromUtf8("plainTextEditHabilidades"))
        self.layoutWidget_6 = QtGui.QWidget(self.widgetCuerpo)
        self.layoutWidget_6.setGeometry(QtCore.QRect(420, 180, 361, 33))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.labelTipoEmpleado = QtGui.QLabel(self.layoutWidget_6)
        self.labelTipoEmpleado.setObjectName(_fromUtf8("labelTipoEmpleado"))
        self.horizontalLayout_3.addWidget(self.labelTipoEmpleado)
        self.comboBoxTipoEmpleado = QtGui.QComboBox(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBoxTipoEmpleado.setFont(font)
        self.comboBoxTipoEmpleado.setObjectName(_fromUtf8("comboBoxTipoEmpleado"))
        self.comboBoxTipoEmpleado.addItem(_fromUtf8(""))
        self.comboBoxTipoEmpleado.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.comboBoxTipoEmpleado)
        self.lineDatosPersonales = QtGui.QFrame(self.widgetCuerpo)
        self.lineDatosPersonales.setGeometry(QtCore.QRect(10, 20, 781, 16))
        self.lineDatosPersonales.setFrameShape(QtGui.QFrame.HLine)
        self.lineDatosPersonales.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineDatosPersonales.setObjectName(_fromUtf8("lineDatosPersonales"))
        self.layoutWidget_8 = QtGui.QWidget(self.widgetCuerpo)
        self.layoutWidget_8.setGeometry(QtCore.QRect(20, 270, 371, 33))
        self.layoutWidget_8.setObjectName(_fromUtf8("layoutWidget_8"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelAniosExperiencia = QtGui.QLabel(self.layoutWidget_8)
        self.labelAniosExperiencia.setObjectName(_fromUtf8("labelAniosExperiencia"))
        self.horizontalLayout.addWidget(self.labelAniosExperiencia)
        self.lineEditAniosExperiencia = QtGui.QLineEdit(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditAniosExperiencia.setFont(font)
        self.lineEditAniosExperiencia.setObjectName(_fromUtf8("lineEditAniosExperiencia"))
        self.horizontalLayout.addWidget(self.lineEditAniosExperiencia)
        self.labelDatosPersonales = QtGui.QLabel(self.widgetCuerpo)
        self.labelDatosPersonales.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.labelDatosPersonales.setObjectName(_fromUtf8("labelDatosPersonales"))
        self.labelEnfermera = QtGui.QLabel(self.widgetCuerpo)
        self.labelEnfermera.setGeometry(QtCore.QRect(20, 230, 81, 16))
        self.labelEnfermera.setObjectName(_fromUtf8("labelEnfermera"))
        self.layoutWidget_9 = QtGui.QWidget(self.widgetCuerpo)
        self.layoutWidget_9.setGeometry(QtCore.QRect(420, 270, 361, 107))
        self.layoutWidget_9.setObjectName(_fromUtf8("layoutWidget_9"))
        self.formLayout_5 = QtGui.QFormLayout(self.layoutWidget_9)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setMargin(0)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.labelEspecialidad = QtGui.QLabel(self.layoutWidget_9)
        self.labelEspecialidad.setObjectName(_fromUtf8("labelEspecialidad"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelEspecialidad)
        self.lineEditEspecialidad = QtGui.QLineEdit(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditEspecialidad.setFont(font)
        self.lineEditEspecialidad.setObjectName(_fromUtf8("lineEditEspecialidad"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditEspecialidad)
        self.labelUniversidad = QtGui.QLabel(self.layoutWidget_9)
        self.labelUniversidad.setObjectName(_fromUtf8("labelUniversidad"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelUniversidad)
        self.lineEditUniversidad = QtGui.QLineEdit(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditUniversidad.setFont(font)
        self.lineEditUniversidad.setObjectName(_fromUtf8("lineEditUniversidad"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditUniversidad)
        self.labelNumeroLicencia = QtGui.QLabel(self.layoutWidget_9)
        self.labelNumeroLicencia.setObjectName(_fromUtf8("labelNumeroLicencia"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelNumeroLicencia)
        self.lineEditNumeroLicencia = QtGui.QLineEdit(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditNumeroLicencia.setFont(font)
        self.lineEditNumeroLicencia.setObjectName(_fromUtf8("lineEditNumeroLicencia"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditNumeroLicencia)
        self.lineMedico = QtGui.QFrame(self.widgetCuerpo)
        self.lineMedico.setGeometry(QtCore.QRect(420, 240, 361, 20))
        self.lineMedico.setFrameShape(QtGui.QFrame.HLine)
        self.lineMedico.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineMedico.setObjectName(_fromUtf8("lineMedico"))
        self.layoutWidget = QtGui.QWidget(self.widgetCuerpo)
        self.layoutWidget.setGeometry(QtCore.QRect(420, 460, 361, 41))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButtonEliminar = QtGui.QPushButton(self.layoutWidget)
        self.pushButtonEliminar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonEliminar.setAutoFillBackground(True)
        self.pushButtonEliminar.setObjectName(_fromUtf8("pushButtonEliminar"))
        self.gridLayout.addWidget(self.pushButtonEliminar, 0, 0, 1, 1)
        self.pushButtonActualizar = QtGui.QPushButton(self.layoutWidget)
        self.pushButtonActualizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonActualizar.setAutoFillBackground(True)
        self.pushButtonActualizar.setObjectName(_fromUtf8("pushButtonActualizar"))
        self.gridLayout.addWidget(self.pushButtonActualizar, 0, 1, 1, 1)
        self.pushButtonCancelar = QtGui.QPushButton(self.layoutWidget)
        self.pushButtonCancelar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonCancelar.setAutoFillBackground(True)
        self.pushButtonCancelar.setObjectName(_fromUtf8("pushButtonCancelar"))
        self.gridLayout.addWidget(self.pushButtonCancelar, 0, 2, 1, 1)
        self.pushButtonAceptar = QtGui.QPushButton(self.layoutWidget)
        self.pushButtonAceptar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonAceptar.setAutoFillBackground(True)
        self.pushButtonAceptar.setObjectName(_fromUtf8("pushButtonAceptar"))
        self.gridLayout.addWidget(self.pushButtonAceptar, 0, 3, 1, 1)

        self.retranslateUi(dialogModificarEmpleado)
        QtCore.QMetaObject.connectSlotsByName(dialogModificarEmpleado)

    def retranslateUi(self, dialogModificarEmpleado):
        dialogModificarEmpleado.setWindowTitle(_translate("dialogModificarEmpleado", "Modificar Empleado", None))
        self.labelColMedica.setText(_translate("dialogModificarEmpleado", "ColMedica", None))
        self.labelClinicManager.setText(_translate("dialogModificarEmpleado", "Clinic Manager", None))
        self.labelIdentificacion.setText(_translate("dialogModificarEmpleado", "Identificacion", None))
        self.labelNombre.setText(_translate("dialogModificarEmpleado", "Nombre", None))
        self.labelDireccion.setText(_translate("dialogModificarEmpleado", "Direccion", None))
        self.labelTelefono.setText(_translate("dialogModificarEmpleado", "Telefono", None))
        self.labelEmail.setText(_translate("dialogModificarEmpleado", "Email", None))
        self.labelHabilidades.setText(_translate("dialogModificarEmpleado", "Habilidades", None))
        self.labelSalario.setText(_translate("dialogModificarEmpleado", "Salario              ", None))
        self.labelCargo.setText(_translate("dialogModificarEmpleado", "Cargo", None))
        self.labelCodigoArea.setText(_translate("dialogModificarEmpleado", "Codigo area", None))
        self.labelCodigoJefe.setText(_translate("dialogModificarEmpleado", "Codigo jefe", None))
        self.labelMedico.setText(_translate("dialogModificarEmpleado", "Medico", None))
        self.labelTipoEmpleado.setText(_translate("dialogModificarEmpleado", "Tipo empleado", None))
        self.comboBoxTipoEmpleado.setItemText(0, _translate("dialogModificarEmpleado", "Enfermera", None))
        self.comboBoxTipoEmpleado.setItemText(1, _translate("dialogModificarEmpleado", "Medico", None))
        self.labelAniosExperiencia.setText(_translate("dialogModificarEmpleado", "Años experiancia", None))
        self.labelDatosPersonales.setText(_translate("dialogModificarEmpleado", "Datos Personales ", None))
        self.labelEnfermera.setText(_translate("dialogModificarEmpleado", "Enfermera", None))
        self.labelEspecialidad.setText(_translate("dialogModificarEmpleado", "Especialidad         ", None))
        self.labelUniversidad.setText(_translate("dialogModificarEmpleado", "Universidad", None))
        self.labelNumeroLicencia.setText(_translate("dialogModificarEmpleado", "Numero licencia", None))
        self.pushButtonEliminar.setText(_translate("dialogModificarEmpleado", "Eliminar", None))
        self.pushButtonActualizar.setText(_translate("dialogModificarEmpleado", "Actualizar", None))
        self.pushButtonCancelar.setText(_translate("dialogModificarEmpleado", "Cancelar", None))
        self.pushButtonAceptar.setText(_translate("dialogModificarEmpleado", "Aceptar", None))


