# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogModificarArea.ui'
#
# Created: Sun Nov  9 13:09:59 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dialogModificarArea(object):
    def setupUi(self, dialogModificarArea):
        dialogModificarArea.setObjectName(_fromUtf8("dialogModificarArea"))
        dialogModificarArea.resize(800, 249)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        dialogModificarArea.setPalette(palette)
        dialogModificarArea.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        dialogModificarArea.setAutoFillBackground(True)
        self.widgetCuerpo = QtGui.QWidget(dialogModificarArea)
        self.widgetCuerpo.setGeometry(QtCore.QRect(10, 70, 781, 161))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setBold(True)
        font.setWeight(75)
        self.widgetCuerpo.setFont(font)
        self.widgetCuerpo.setAutoFillBackground(True)
        self.widgetCuerpo.setObjectName(_fromUtf8("widgetCuerpo"))
        self.layoutWidget = QtGui.QWidget(self.widgetCuerpo)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 761, 89))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.comboBoxCodigo = QtGui.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBoxCodigo.setFont(font)
        self.comboBoxCodigo.setObjectName(_fromUtf8("comboBoxCodigo"))
        self.gridLayout.addWidget(self.comboBoxCodigo, 0, 2, 1, 1)
        self.labelCodigo = QtGui.QLabel(self.layoutWidget)
        self.labelCodigo.setObjectName(_fromUtf8("labelCodigo"))
        self.gridLayout.addWidget(self.labelCodigo, 0, 0, 1, 1)
        self.lineEditDescripcion = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditDescripcion.setFont(font)
        self.lineEditDescripcion.setObjectName(_fromUtf8("lineEditDescripcion"))
        self.gridLayout.addWidget(self.lineEditDescripcion, 2, 2, 1, 1)
        self.labelDescripcion = QtGui.QLabel(self.layoutWidget)
        self.labelDescripcion.setObjectName(_fromUtf8("labelDescripcion"))
        self.gridLayout.addWidget(self.labelDescripcion, 2, 0, 1, 1)
        self.labelNombre = QtGui.QLabel(self.layoutWidget)
        self.labelNombre.setObjectName(_fromUtf8("labelNombre"))
        self.gridLayout.addWidget(self.labelNombre, 1, 0, 1, 1)
        self.lineEditNombre = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditNombre.setFont(font)
        self.lineEditNombre.setObjectName(_fromUtf8("lineEditNombre"))
        self.gridLayout.addWidget(self.lineEditNombre, 1, 2, 1, 1)
        self.layoutWidget_2 = QtGui.QWidget(self.widgetCuerpo)
        self.layoutWidget_2.setGeometry(QtCore.QRect(410, 120, 361, 29))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButtonActualizar = QtGui.QPushButton(self.layoutWidget_2)
        self.pushButtonActualizar.setObjectName(_fromUtf8("pushButtonActualizar"))
        self.horizontalLayout.addWidget(self.pushButtonActualizar)
        self.pushButtonEliminar = QtGui.QPushButton(self.layoutWidget_2)
        self.pushButtonEliminar.setObjectName(_fromUtf8("pushButtonEliminar"))
        self.horizontalLayout.addWidget(self.pushButtonEliminar)
        self.pushButtonCancelar = QtGui.QPushButton(self.layoutWidget_2)
        self.pushButtonCancelar.setObjectName(_fromUtf8("pushButtonCancelar"))
        self.horizontalLayout.addWidget(self.pushButtonCancelar)
        self.pushButtonAceptar = QtGui.QPushButton(self.layoutWidget_2)
        self.pushButtonAceptar.setObjectName(_fromUtf8("pushButtonAceptar"))
        self.horizontalLayout.addWidget(self.pushButtonAceptar)
        self.widgetCabecera = QtGui.QWidget(dialogModificarArea)
        self.widgetCabecera.setGeometry(QtCore.QRect(0, 0, 800, 65))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widgetCabecera.setPalette(palette)
        self.widgetCabecera.setAutoFillBackground(True)
        self.widgetCabecera.setObjectName(_fromUtf8("widgetCabecera"))
        self.layoutWidget_4 = QtGui.QWidget(self.widgetCabecera)
        self.layoutWidget_4.setGeometry(QtCore.QRect(20, 0, 162, 63))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.formLayout_5 = QtGui.QFormLayout(self.layoutWidget_4)
        self.formLayout_5.setMargin(0)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.labelColMedica = QtGui.QLabel(self.layoutWidget_4)
        self.labelColMedica.setStyleSheet(_fromUtf8("font: 30pt \"Ubuntu Condensed\";\n"
"color: rgb(255, 255, 255);"))
        self.labelColMedica.setObjectName(_fromUtf8("labelColMedica"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelColMedica)
        self.labelClinicManager = QtGui.QLabel(self.layoutWidget_4)
        self.labelClinicManager.setObjectName(_fromUtf8("labelClinicManager"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelClinicManager)

        self.retranslateUi(dialogModificarArea)
        QtCore.QMetaObject.connectSlotsByName(dialogModificarArea)

    def retranslateUi(self, dialogModificarArea):
        dialogModificarArea.setWindowTitle(_translate("dialogModificarArea", "Modificar Area", None))
        self.labelCodigo.setText(_translate("dialogModificarArea", "Codigo", None))
        self.labelDescripcion.setText(_translate("dialogModificarArea", "Descripcion", None))
        self.labelNombre.setText(_translate("dialogModificarArea", "Nombre", None))
        self.pushButtonActualizar.setText(_translate("dialogModificarArea", "Actualizar", None))
        self.pushButtonEliminar.setText(_translate("dialogModificarArea", "Eliminar", None))
        self.pushButtonCancelar.setText(_translate("dialogModificarArea", "Cancelar", None))
        self.pushButtonAceptar.setText(_translate("dialogModificarArea", "Aceptar", None))
        self.labelColMedica.setText(_translate("dialogModificarArea", "ColMedica", None))
        self.labelClinicManager.setText(_translate("dialogModificarArea", "Clinic Manager", None))

