# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogModificarMedicamento.ui'
#
# Created: Sun Nov  9 16:25:27 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dialogModificarMedicamento(object):
    def setupUi(self, dialogModificarMedicamento):
        dialogModificarMedicamento.setObjectName(_fromUtf8("dialogModificarMedicamento"))
        dialogModificarMedicamento.resize(800, 330)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        dialogModificarMedicamento.setPalette(palette)
        dialogModificarMedicamento.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        dialogModificarMedicamento.setAutoFillBackground(True)
        self.widgetCabecera = QtGui.QWidget(dialogModificarMedicamento)
        self.widgetCabecera.setGeometry(QtCore.QRect(0, 0, 800, 65))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widgetCabecera.setPalette(palette)
        self.widgetCabecera.setAutoFillBackground(True)
        self.widgetCabecera.setObjectName(_fromUtf8("widgetCabecera"))
        self.layoutWidget_4 = QtGui.QWidget(self.widgetCabecera)
        self.layoutWidget_4.setGeometry(QtCore.QRect(20, 0, 162, 63))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.formLayout_5 = QtGui.QFormLayout(self.layoutWidget_4)
        self.formLayout_5.setMargin(0)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.labelColMedica = QtGui.QLabel(self.layoutWidget_4)
        self.labelColMedica.setStyleSheet(_fromUtf8("font: 30pt \"Ubuntu Condensed\";\n"
"color: rgb(255, 255, 255);"))
        self.labelColMedica.setObjectName(_fromUtf8("labelColMedica"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelColMedica)
        self.labelClinicManager = QtGui.QLabel(self.layoutWidget_4)
        self.labelClinicManager.setObjectName(_fromUtf8("labelClinicManager"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelClinicManager)
        self.widget = QtGui.QWidget(dialogModificarMedicamento)
        self.widget.setGeometry(QtCore.QRect(10, 80, 781, 241))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setBold(True)
        font.setWeight(75)
        self.widget.setFont(font)
        self.widget.setAutoFillBackground(True)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.layoutWidget = QtGui.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 771, 141))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineEditDescripcion = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditDescripcion.setFont(font)
        self.lineEditDescripcion.setObjectName(_fromUtf8("lineEditDescripcion"))
        self.gridLayout.addWidget(self.lineEditDescripcion, 3, 1, 1, 1)
        self.labelDescripcion = QtGui.QLabel(self.layoutWidget)
        self.labelDescripcion.setObjectName(_fromUtf8("labelDescripcion"))
        self.gridLayout.addWidget(self.labelDescripcion, 3, 0, 1, 1)
        self.lineEditNombre = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditNombre.setFont(font)
        self.lineEditNombre.setObjectName(_fromUtf8("lineEditNombre"))
        self.gridLayout.addWidget(self.lineEditNombre, 1, 1, 1, 1)
        self.labelCosto = QtGui.QLabel(self.layoutWidget)
        self.labelCosto.setObjectName(_fromUtf8("labelCosto"))
        self.gridLayout.addWidget(self.labelCosto, 2, 0, 1, 1)
        self.labelCodigo = QtGui.QLabel(self.layoutWidget)
        self.labelCodigo.setObjectName(_fromUtf8("labelCodigo"))
        self.gridLayout.addWidget(self.labelCodigo, 0, 0, 1, 1)
        self.labelNombre = QtGui.QLabel(self.layoutWidget)
        self.labelNombre.setObjectName(_fromUtf8("labelNombre"))
        self.gridLayout.addWidget(self.labelNombre, 1, 0, 1, 1)
        self.lineEditCosto = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditCosto.setFont(font)
        self.lineEditCosto.setObjectName(_fromUtf8("lineEditCosto"))
        self.gridLayout.addWidget(self.lineEditCosto, 2, 1, 1, 1)
        self.comboBoxCodigo = QtGui.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBoxCodigo.setFont(font)
        self.comboBoxCodigo.setObjectName(_fromUtf8("comboBoxCodigo"))
        self.gridLayout.addWidget(self.comboBoxCodigo, 0, 1, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(self.widget)
        self.layoutWidget1.setGeometry(QtCore.QRect(410, 200, 360, 29))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButtonEliminar = QtGui.QPushButton(self.layoutWidget1)
        self.pushButtonEliminar.setObjectName(_fromUtf8("pushButtonEliminar"))
        self.gridLayout_2.addWidget(self.pushButtonEliminar, 0, 0, 1, 1)
        self.pushButtonActualizar = QtGui.QPushButton(self.layoutWidget1)
        self.pushButtonActualizar.setObjectName(_fromUtf8("pushButtonActualizar"))
        self.gridLayout_2.addWidget(self.pushButtonActualizar, 0, 1, 1, 1)
        self.pushButtonCancelar = QtGui.QPushButton(self.layoutWidget1)
        self.pushButtonCancelar.setObjectName(_fromUtf8("pushButtonCancelar"))
        self.gridLayout_2.addWidget(self.pushButtonCancelar, 0, 2, 1, 1)
        self.pushButtonAceptar = QtGui.QPushButton(self.layoutWidget1)
        self.pushButtonAceptar.setObjectName(_fromUtf8("pushButtonAceptar"))
        self.gridLayout_2.addWidget(self.pushButtonAceptar, 0, 3, 1, 1)

        self.retranslateUi(dialogModificarMedicamento)
        QtCore.QMetaObject.connectSlotsByName(dialogModificarMedicamento)

    def retranslateUi(self, dialogModificarMedicamento):
        dialogModificarMedicamento.setWindowTitle(_translate("dialogModificarMedicamento", "Modificar medicamento", None))
        self.labelColMedica.setText(_translate("dialogModificarMedicamento", "ColMedica", None))
        self.labelClinicManager.setText(_translate("dialogModificarMedicamento", "Clinic Manager", None))
        self.labelDescripcion.setText(_translate("dialogModificarMedicamento", "Descripcion", None))
        self.labelCosto.setText(_translate("dialogModificarMedicamento", "Costo", None))
        self.labelCodigo.setText(_translate("dialogModificarMedicamento", "Codigo", None))
        self.labelNombre.setText(_translate("dialogModificarMedicamento", "Nombre", None))
        self.pushButtonEliminar.setText(_translate("dialogModificarMedicamento", "Eliminar", None))
        self.pushButtonActualizar.setText(_translate("dialogModificarMedicamento", "Actualizar", None))
        self.pushButtonCancelar.setText(_translate("dialogModificarMedicamento", "Cancelar", None))
        self.pushButtonAceptar.setText(_translate("dialogModificarMedicamento", "Aceptar", None))

