# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogNuevaCama.ui'
#
# Created: Sun Nov  9 14:53:07 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dialogNuevaCama(object):
    def setupUi(self, dialogNuevaCama):
        dialogNuevaCama.setObjectName(_fromUtf8("dialogNuevaCama"))
        dialogNuevaCama.resize(800, 320)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        dialogNuevaCama.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setBold(True)
        font.setWeight(75)
        dialogNuevaCama.setFont(font)
        dialogNuevaCama.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        dialogNuevaCama.setAutoFillBackground(True)
        self.widgetCuerpo = QtGui.QWidget(dialogNuevaCama)
        self.widgetCuerpo.setGeometry(QtCore.QRect(10, 70, 781, 241))
        self.widgetCuerpo.setAutoFillBackground(True)
        self.widgetCuerpo.setObjectName(_fromUtf8("widgetCuerpo"))
        self.layoutWidget = QtGui.QWidget(self.widgetCuerpo)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 761, 110))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelCodigoArea = QtGui.QLabel(self.layoutWidget)
        self.labelCodigoArea.setObjectName(_fromUtf8("labelCodigoArea"))
        self.gridLayout.addWidget(self.labelCodigoArea, 0, 0, 1, 1)
        self.comboBoxCodigoArea = QtGui.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBoxCodigoArea.setFont(font)
        self.comboBoxCodigoArea.setObjectName(_fromUtf8("comboBoxCodigoArea"))
        self.gridLayout.addWidget(self.comboBoxCodigoArea, 0, 1, 1, 1)
        self.labelDescripcion = QtGui.QLabel(self.layoutWidget)
        self.labelDescripcion.setObjectName(_fromUtf8("labelDescripcion"))
        self.gridLayout.addWidget(self.labelDescripcion, 2, 0, 1, 1)
        self.labelNumerDeCama = QtGui.QLabel(self.layoutWidget)
        self.labelNumerDeCama.setObjectName(_fromUtf8("labelNumerDeCama"))
        self.gridLayout.addWidget(self.labelNumerDeCama, 1, 0, 1, 1)
        self.lineEditNumeroDeCama = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditNumeroDeCama.setFont(font)
        self.lineEditNumeroDeCama.setReadOnly(True)
        self.lineEditNumeroDeCama.setObjectName(_fromUtf8("lineEditNumeroDeCama"))
        self.gridLayout.addWidget(self.lineEditNumeroDeCama, 1, 1, 1, 1)
        self.lineEditDescripcion = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditDescripcion.setFont(font)
        self.lineEditDescripcion.setObjectName(_fromUtf8("lineEditDescripcion"))
        self.gridLayout.addWidget(self.lineEditDescripcion, 2, 1, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(self.widgetCuerpo)
        self.layoutWidget1.setGeometry(QtCore.QRect(590, 200, 178, 29))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButtonCancelar = QtGui.QPushButton(self.layoutWidget1)
        self.pushButtonCancelar.setObjectName(_fromUtf8("pushButtonCancelar"))
        self.horizontalLayout.addWidget(self.pushButtonCancelar)
        self.pushButtonAceptar = QtGui.QPushButton(self.layoutWidget1)
        self.pushButtonAceptar.setObjectName(_fromUtf8("pushButtonAceptar"))
        self.horizontalLayout.addWidget(self.pushButtonAceptar)
        self.widgetCabecera = QtGui.QWidget(dialogNuevaCama)
        self.widgetCabecera.setGeometry(QtCore.QRect(0, 0, 800, 65))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widgetCabecera.setPalette(palette)
        self.widgetCabecera.setAutoFillBackground(True)
        self.widgetCabecera.setObjectName(_fromUtf8("widgetCabecera"))
        self.layoutWidget_4 = QtGui.QWidget(self.widgetCabecera)
        self.layoutWidget_4.setGeometry(QtCore.QRect(20, 0, 162, 63))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.formLayout_5 = QtGui.QFormLayout(self.layoutWidget_4)
        self.formLayout_5.setMargin(0)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.labelColMedica = QtGui.QLabel(self.layoutWidget_4)
        self.labelColMedica.setStyleSheet(_fromUtf8("font: 30pt \"Ubuntu Condensed\";\n"
"color: rgb(255, 255, 255);"))
        self.labelColMedica.setObjectName(_fromUtf8("labelColMedica"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelColMedica)
        self.labelClinicManager = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelClinicManager.setFont(font)
        self.labelClinicManager.setObjectName(_fromUtf8("labelClinicManager"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelClinicManager)

        self.retranslateUi(dialogNuevaCama)
        QtCore.QMetaObject.connectSlotsByName(dialogNuevaCama)

    def retranslateUi(self, dialogNuevaCama):
        dialogNuevaCama.setWindowTitle(_translate("dialogNuevaCama", "Nueva Cama", None))
        self.labelCodigoArea.setText(_translate("dialogNuevaCama", "Codigo area", None))
        self.labelDescripcion.setText(_translate("dialogNuevaCama", "Descripcion", None))
        self.labelNumerDeCama.setText(_translate("dialogNuevaCama", "Numero de cama", None))
        self.lineEditNumeroDeCama.setText(_translate("dialogNuevaCama", "AUTOMATICO", None))
        self.pushButtonCancelar.setText(_translate("dialogNuevaCama", "Cancelar", None))
        self.pushButtonAceptar.setText(_translate("dialogNuevaCama", "Aceptar", None))
        self.labelColMedica.setText(_translate("dialogNuevaCama", "ColMedica", None))
        self.labelClinicManager.setText(_translate("dialogNuevaCama", "Clinic Manager", None))

