# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogNuevoEmpleado.ui'
#
# Created: Sun Nov  9 12:48:48 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dialogNuevoEmpleado(object):
    def setupUi(self, dialogNuevoEmpleado):
        dialogNuevoEmpleado.setObjectName(_fromUtf8("dialogNuevoEmpleado"))
        dialogNuevoEmpleado.resize(800, 600)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        dialogNuevoEmpleado.setPalette(palette)
        dialogNuevoEmpleado.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        dialogNuevoEmpleado.setAutoFillBackground(True)
        self.widgetCabecera = QtGui.QWidget(dialogNuevoEmpleado)
        self.widgetCabecera.setGeometry(QtCore.QRect(0, 0, 800, 65))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widgetCabecera.setPalette(palette)
        self.widgetCabecera.setAutoFillBackground(True)
        self.widgetCabecera.setObjectName(_fromUtf8("widgetCabecera"))
        self.layoutWidget_4 = QtGui.QWidget(self.widgetCabecera)
        self.layoutWidget_4.setGeometry(QtCore.QRect(20, 0, 162, 63))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.formLayout_5 = QtGui.QFormLayout(self.layoutWidget_4)
        self.formLayout_5.setMargin(0)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.labelColMedica = QtGui.QLabel(self.layoutWidget_4)
        self.labelColMedica.setStyleSheet(_fromUtf8("font: 30pt \"Ubuntu Condensed\";\n"
"color: rgb(255, 255, 255);"))
        self.labelColMedica.setObjectName(_fromUtf8("labelColMedica"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelColMedica)
        self.labelClinicManager = QtGui.QLabel(self.layoutWidget_4)
        self.labelClinicManager.setObjectName(_fromUtf8("labelClinicManager"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelClinicManager)
        self.widgetCuerpo = QtGui.QWidget(dialogNuevoEmpleado)
        self.widgetCuerpo.setGeometry(QtCore.QRect(0, 70, 800, 511))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setBold(True)
        font.setWeight(75)
        self.widgetCuerpo.setFont(font)
        self.widgetCuerpo.setAutoFillBackground(True)
        self.widgetCuerpo.setObjectName(_fromUtf8("widgetCuerpo"))
        self.layoutWidget = QtGui.QWidget(self.widgetCuerpo)
        self.layoutWidget.setGeometry(QtCore.QRect(610, 480, 178, 31))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButtonCancelar = QtGui.QPushButton(self.layoutWidget)
        self.pushButtonCancelar.setObjectName(_fromUtf8("pushButtonCancelar"))
        self.horizontalLayout_2.addWidget(self.pushButtonCancelar)
        self.pushButtonAceptar = QtGui.QPushButton(self.layoutWidget)
        self.pushButtonAceptar.setObjectName(_fromUtf8("pushButtonAceptar"))
        self.horizontalLayout_2.addWidget(self.pushButtonAceptar)
        self.layoutWidget_2 = QtGui.QWidget(self.widgetCuerpo)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 40, 371, 171))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.formLayout = QtGui.QFormLayout(self.layoutWidget_2)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.labelIdentificacion = QtGui.QLabel(self.layoutWidget_2)
        self.labelIdentificacion.setObjectName(_fromUtf8("labelIdentificacion"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelIdentificacion)
        self.lineEditIdentificacion = QtGui.QLineEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditIdentificacion.setFont(font)
        self.lineEditIdentificacion.setObjectName(_fromUtf8("lineEditIdentificacion"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditIdentificacion)
        self.labelNombre = QtGui.QLabel(self.layoutWidget_2)
        self.labelNombre.setObjectName(_fromUtf8("labelNombre"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelNombre)
        self.lineEditNombre = QtGui.QLineEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditNombre.setFont(font)
        self.lineEditNombre.setObjectName(_fromUtf8("lineEditNombre"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditNombre)
        self.labelDireccion = QtGui.QLabel(self.layoutWidget_2)
        self.labelDireccion.setObjectName(_fromUtf8("labelDireccion"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelDireccion)
        self.lineEditDireccion = QtGui.QLineEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditDireccion.setFont(font)
        self.lineEditDireccion.setObjectName(_fromUtf8("lineEditDireccion"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditDireccion)
        self.labelTelefono = QtGui.QLabel(self.layoutWidget_2)
        self.labelTelefono.setObjectName(_fromUtf8("labelTelefono"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelTelefono)
        self.lineEditTelefono = QtGui.QLineEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditTelefono.setFont(font)
        self.lineEditTelefono.setObjectName(_fromUtf8("lineEditTelefono"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditTelefono)
        self.labelEmail = QtGui.QLabel(self.layoutWidget_2)
        self.labelEmail.setObjectName(_fromUtf8("labelEmail"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.labelEmail)
        self.lineEditEmail = QtGui.QLineEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditEmail.setFont(font)
        self.lineEditEmail.setObjectName(_fromUtf8("lineEditEmail"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEditEmail)
        self.labelHabilidades = QtGui.QLabel(self.widgetCuerpo)
        self.labelHabilidades.setGeometry(QtCore.QRect(20, 330, 369, 27))
        self.labelHabilidades.setObjectName(_fromUtf8("labelHabilidades"))
        self.lineEnfermera = QtGui.QFrame(self.widgetCuerpo)
        self.lineEnfermera.setGeometry(QtCore.QRect(20, 250, 371, 20))
        self.lineEnfermera.setFrameShape(QtGui.QFrame.HLine)
        self.lineEnfermera.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineEnfermera.setObjectName(_fromUtf8("lineEnfermera"))
        self.layoutWidget_3 = QtGui.QWidget(self.widgetCuerpo)
        self.layoutWidget_3.setGeometry(QtCore.QRect(420, 40, 361, 136))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.formLayout_2 = QtGui.QFormLayout(self.layoutWidget_3)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.labelSalario = QtGui.QLabel(self.layoutWidget_3)
        self.labelSalario.setObjectName(_fromUtf8("labelSalario"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelSalario)
        self.lineEditSalario = QtGui.QLineEdit(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditSalario.setFont(font)
        self.lineEditSalario.setObjectName(_fromUtf8("lineEditSalario"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditSalario)
        self.labelCargo = QtGui.QLabel(self.layoutWidget_3)
        self.labelCargo.setObjectName(_fromUtf8("labelCargo"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelCargo)
        self.lineEditCargo = QtGui.QLineEdit(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditCargo.setFont(font)
        self.lineEditCargo.setObjectName(_fromUtf8("lineEditCargo"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditCargo)
        self.labelCodigoArea = QtGui.QLabel(self.layoutWidget_3)
        self.labelCodigoArea.setObjectName(_fromUtf8("labelCodigoArea"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelCodigoArea)
        self.comboBoxCodigoArea = QtGui.QComboBox(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBoxCodigoArea.setFont(font)
        self.comboBoxCodigoArea.setObjectName(_fromUtf8("comboBoxCodigoArea"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboBoxCodigoArea)
        self.labelCodigoJefe = QtGui.QLabel(self.layoutWidget_3)
        self.labelCodigoJefe.setObjectName(_fromUtf8("labelCodigoJefe"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelCodigoJefe)
        self.comboBoxCodigoJefe = QtGui.QComboBox(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBoxCodigoJefe.setFont(font)
        self.comboBoxCodigoJefe.setObjectName(_fromUtf8("comboBoxCodigoJefe"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.comboBoxCodigoJefe)
        self.labelMedico = QtGui.QLabel(self.widgetCuerpo)
        self.labelMedico.setGeometry(QtCore.QRect(420, 240, 81, 16))
        self.labelMedico.setObjectName(_fromUtf8("labelMedico"))
        self.plainTextEditHabilidades = QtGui.QPlainTextEdit(self.widgetCuerpo)
        self.plainTextEditHabilidades.setGeometry(QtCore.QRect(20, 360, 371, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.plainTextEditHabilidades.setFont(font)
        self.plainTextEditHabilidades.setObjectName(_fromUtf8("plainTextEditHabilidades"))
        self.layoutWidget_5 = QtGui.QWidget(self.widgetCuerpo)
        self.layoutWidget_5.setGeometry(QtCore.QRect(420, 190, 361, 31))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.labelTipoEmpleado = QtGui.QLabel(self.layoutWidget_5)
        self.labelTipoEmpleado.setObjectName(_fromUtf8("labelTipoEmpleado"))
        self.horizontalLayout_3.addWidget(self.labelTipoEmpleado)
        self.comboBoxTipoEmpleado = QtGui.QComboBox(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBoxTipoEmpleado.setFont(font)
        self.comboBoxTipoEmpleado.setObjectName(_fromUtf8("comboBoxTipoEmpleado"))
        self.comboBoxTipoEmpleado.addItem(_fromUtf8(""))
        self.comboBoxTipoEmpleado.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.comboBoxTipoEmpleado)
        self.lineDatosPersonales = QtGui.QFrame(self.widgetCuerpo)
        self.lineDatosPersonales.setGeometry(QtCore.QRect(10, 20, 781, 16))
        self.lineDatosPersonales.setFrameShape(QtGui.QFrame.HLine)
        self.lineDatosPersonales.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineDatosPersonales.setObjectName(_fromUtf8("lineDatosPersonales"))
        self.layoutWidget_6 = QtGui.QWidget(self.widgetCuerpo)
        self.layoutWidget_6.setGeometry(QtCore.QRect(20, 280, 371, 31))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelAniosExperiencia = QtGui.QLabel(self.layoutWidget_6)
        self.labelAniosExperiencia.setObjectName(_fromUtf8("labelAniosExperiencia"))
        self.horizontalLayout.addWidget(self.labelAniosExperiencia)
        self.lineEditAniosExperiencia = QtGui.QLineEdit(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditAniosExperiencia.setFont(font)
        self.lineEditAniosExperiencia.setObjectName(_fromUtf8("lineEditAniosExperiencia"))
        self.horizontalLayout.addWidget(self.lineEditAniosExperiencia)
        self.labelDatosPersonales = QtGui.QLabel(self.widgetCuerpo)
        self.labelDatosPersonales.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.labelDatosPersonales.setObjectName(_fromUtf8("labelDatosPersonales"))
        self.labelEnfermera = QtGui.QLabel(self.widgetCuerpo)
        self.labelEnfermera.setGeometry(QtCore.QRect(20, 240, 81, 16))
        self.labelEnfermera.setObjectName(_fromUtf8("labelEnfermera"))
        self.layoutWidget_7 = QtGui.QWidget(self.widgetCuerpo)
        self.layoutWidget_7.setGeometry(QtCore.QRect(420, 290, 361, 101))
        self.layoutWidget_7.setObjectName(_fromUtf8("layoutWidget_7"))
        self.formLayout_3 = QtGui.QFormLayout(self.layoutWidget_7)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.labelEspecialidad = QtGui.QLabel(self.layoutWidget_7)
        self.labelEspecialidad.setObjectName(_fromUtf8("labelEspecialidad"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelEspecialidad)
        self.lineEditEspecialidad = QtGui.QLineEdit(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditEspecialidad.setFont(font)
        self.lineEditEspecialidad.setObjectName(_fromUtf8("lineEditEspecialidad"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditEspecialidad)
        self.labelUniversidad = QtGui.QLabel(self.layoutWidget_7)
        self.labelUniversidad.setObjectName(_fromUtf8("labelUniversidad"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelUniversidad)
        self.lineEditUniversidad = QtGui.QLineEdit(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditUniversidad.setFont(font)
        self.lineEditUniversidad.setObjectName(_fromUtf8("lineEditUniversidad"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditUniversidad)
        self.labelNumeroLicencia = QtGui.QLabel(self.layoutWidget_7)
        self.labelNumeroLicencia.setObjectName(_fromUtf8("labelNumeroLicencia"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelNumeroLicencia)
        self.lineEditNumeroLicencia = QtGui.QLineEdit(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditNumeroLicencia.setFont(font)
        self.lineEditNumeroLicencia.setObjectName(_fromUtf8("lineEditNumeroLicencia"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditNumeroLicencia)
        self.lineMedico = QtGui.QFrame(self.widgetCuerpo)
        self.lineMedico.setGeometry(QtCore.QRect(420, 250, 361, 20))
        self.lineMedico.setFrameShape(QtGui.QFrame.HLine)
        self.lineMedico.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineMedico.setObjectName(_fromUtf8("lineMedico"))

        self.retranslateUi(dialogNuevoEmpleado)
        QtCore.QMetaObject.connectSlotsByName(dialogNuevoEmpleado)

    def retranslateUi(self, dialogNuevoEmpleado):
        dialogNuevoEmpleado.setWindowTitle(_translate("dialogNuevoEmpleado", "Nuevo Empleado", None))
        self.labelColMedica.setText(_translate("dialogNuevoEmpleado", "ColMedica", None))
        self.labelClinicManager.setText(_translate("dialogNuevoEmpleado", "Clinic Manager", None))
        self.pushButtonCancelar.setText(_translate("dialogNuevoEmpleado", "Cancelar", None))
        self.pushButtonAceptar.setText(_translate("dialogNuevoEmpleado", "Aceptar", None))
        self.labelIdentificacion.setText(_translate("dialogNuevoEmpleado", "Identificacion", None))
        self.labelNombre.setText(_translate("dialogNuevoEmpleado", "Nombre", None))
        self.labelDireccion.setText(_translate("dialogNuevoEmpleado", "Direccion", None))
        self.labelTelefono.setText(_translate("dialogNuevoEmpleado", "Telefono", None))
        self.labelEmail.setText(_translate("dialogNuevoEmpleado", "Email", None))
        self.labelHabilidades.setText(_translate("dialogNuevoEmpleado", "Habilidades", None))
        self.labelSalario.setText(_translate("dialogNuevoEmpleado", "Salario              ", None))
        self.labelCargo.setText(_translate("dialogNuevoEmpleado", "Cargo", None))
        self.labelCodigoArea.setText(_translate("dialogNuevoEmpleado", "Codigo area", None))
        self.labelCodigoJefe.setText(_translate("dialogNuevoEmpleado", "Codigo jefe", None))
        self.labelMedico.setText(_translate("dialogNuevoEmpleado", "Medico", None))
        self.labelTipoEmpleado.setText(_translate("dialogNuevoEmpleado", "Tipo empleado", None))
        self.comboBoxTipoEmpleado.setItemText(0, _translate("dialogNuevoEmpleado", "Enfermera", None))
        self.comboBoxTipoEmpleado.setItemText(1, _translate("dialogNuevoEmpleado", "Medico", None))
        self.labelAniosExperiencia.setText(_translate("dialogNuevoEmpleado", "Años experiancia", None))
        self.labelDatosPersonales.setText(_translate("dialogNuevoEmpleado", "Datos Personales ", None))
        self.labelEnfermera.setText(_translate("dialogNuevoEmpleado", "Enfermera", None))
        self.labelEspecialidad.setText(_translate("dialogNuevoEmpleado", "Especialidad         ", None))
        self.labelUniversidad.setText(_translate("dialogNuevoEmpleado", "Universidad", None))
        self.labelNumeroLicencia.setText(_translate("dialogNuevoEmpleado", "Numero licencia", None))

