# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogNuevoMedicamento.ui'
#
# Created: Sun Nov  9 16:25:10 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dialogNuevoMedicamento(object):
    def setupUi(self, dialogNuevoMedicamento):
        dialogNuevoMedicamento.setObjectName(_fromUtf8("dialogNuevoMedicamento"))
        dialogNuevoMedicamento.resize(800, 330)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        dialogNuevoMedicamento.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setBold(True)
        font.setWeight(75)
        dialogNuevoMedicamento.setFont(font)
        dialogNuevoMedicamento.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        dialogNuevoMedicamento.setAutoFillBackground(False)
        self.widgetCabecera = QtGui.QWidget(dialogNuevoMedicamento)
        self.widgetCabecera.setGeometry(QtCore.QRect(0, 0, 800, 65))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widgetCabecera.setPalette(palette)
        self.widgetCabecera.setAutoFillBackground(True)
        self.widgetCabecera.setObjectName(_fromUtf8("widgetCabecera"))
        self.layoutWidget_4 = QtGui.QWidget(self.widgetCabecera)
        self.layoutWidget_4.setGeometry(QtCore.QRect(20, 0, 162, 63))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.formLayout_5 = QtGui.QFormLayout(self.layoutWidget_4)
        self.formLayout_5.setMargin(0)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.labelColMedica = QtGui.QLabel(self.layoutWidget_4)
        self.labelColMedica.setStyleSheet(_fromUtf8("font: 30pt \"Ubuntu Condensed\";\n"
"color: rgb(255, 255, 255);"))
        self.labelColMedica.setObjectName(_fromUtf8("labelColMedica"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelColMedica)
        self.labelClinicManager = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelClinicManager.setFont(font)
        self.labelClinicManager.setObjectName(_fromUtf8("labelClinicManager"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelClinicManager)
        self.widgetCuerpo = QtGui.QWidget(dialogNuevoMedicamento)
        self.widgetCuerpo.setGeometry(QtCore.QRect(10, 80, 781, 241))
        self.widgetCuerpo.setAutoFillBackground(True)
        self.widgetCuerpo.setObjectName(_fromUtf8("widgetCuerpo"))
        self.layoutWidget = QtGui.QWidget(self.widgetCuerpo)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 771, 141))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineEditDescripcion = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditDescripcion.setFont(font)
        self.lineEditDescripcion.setObjectName(_fromUtf8("lineEditDescripcion"))
        self.gridLayout.addWidget(self.lineEditDescripcion, 3, 1, 1, 1)
        self.labelDescripcion = QtGui.QLabel(self.layoutWidget)
        self.labelDescripcion.setObjectName(_fromUtf8("labelDescripcion"))
        self.gridLayout.addWidget(self.labelDescripcion, 3, 0, 1, 1)
        self.lineEditNombre = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditNombre.setFont(font)
        self.lineEditNombre.setObjectName(_fromUtf8("lineEditNombre"))
        self.gridLayout.addWidget(self.lineEditNombre, 1, 1, 1, 1)
        self.labelCosto = QtGui.QLabel(self.layoutWidget)
        self.labelCosto.setObjectName(_fromUtf8("labelCosto"))
        self.gridLayout.addWidget(self.labelCosto, 2, 0, 1, 1)
        self.labelCodigo = QtGui.QLabel(self.layoutWidget)
        self.labelCodigo.setObjectName(_fromUtf8("labelCodigo"))
        self.gridLayout.addWidget(self.labelCodigo, 0, 0, 1, 1)
        self.labelNombre = QtGui.QLabel(self.layoutWidget)
        self.labelNombre.setObjectName(_fromUtf8("labelNombre"))
        self.gridLayout.addWidget(self.labelNombre, 1, 0, 1, 1)
        self.lineEditCosto = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditCosto.setFont(font)
        self.lineEditCosto.setObjectName(_fromUtf8("lineEditCosto"))
        self.gridLayout.addWidget(self.lineEditCosto, 2, 1, 1, 1)
        self.lineEditCodigo = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditCodigo.setFont(font)
        self.lineEditCodigo.setObjectName(_fromUtf8("lineEditCodigo"))
        self.gridLayout.addWidget(self.lineEditCodigo, 0, 1, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(self.widgetCuerpo)
        self.layoutWidget1.setGeometry(QtCore.QRect(600, 200, 178, 29))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButtonCancelar = QtGui.QPushButton(self.layoutWidget1)
        self.pushButtonCancelar.setObjectName(_fromUtf8("pushButtonCancelar"))
        self.horizontalLayout.addWidget(self.pushButtonCancelar)
        self.pushButtonAceptar = QtGui.QPushButton(self.layoutWidget1)
        self.pushButtonAceptar.setObjectName(_fromUtf8("pushButtonAceptar"))
        self.horizontalLayout.addWidget(self.pushButtonAceptar)

        self.retranslateUi(dialogNuevoMedicamento)
        QtCore.QMetaObject.connectSlotsByName(dialogNuevoMedicamento)

    def retranslateUi(self, dialogNuevoMedicamento):
        dialogNuevoMedicamento.setWindowTitle(_translate("dialogNuevoMedicamento", "Nuevo medicamento", None))
        self.labelColMedica.setText(_translate("dialogNuevoMedicamento", "ColMedica", None))
        self.labelClinicManager.setText(_translate("dialogNuevoMedicamento", "Clinic Manager", None))
        self.labelDescripcion.setText(_translate("dialogNuevoMedicamento", "Descripcion", None))
        self.labelCosto.setText(_translate("dialogNuevoMedicamento", "Costo", None))
        self.labelCodigo.setText(_translate("dialogNuevoMedicamento", "Codigo", None))
        self.labelNombre.setText(_translate("dialogNuevoMedicamento", "Nombre", None))
        self.pushButtonCancelar.setText(_translate("dialogNuevoMedicamento", "Cancelar", None))
        self.pushButtonAceptar.setText(_translate("dialogNuevoMedicamento", "Aceptar", None))

