# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created: Sat Nov  8 22:55:44 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindowIniciarSesion(object):
    def setupUi(self, MainWindowIniciarSesion):
        MainWindowIniciarSesion.setObjectName(_fromUtf8("MainWindowIniciarSesion"))
        MainWindowIniciarSesion.resize(800, 600)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindowIniciarSesion.setPalette(palette)
        MainWindowIniciarSesion.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        MainWindowIniciarSesion.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindowIniciarSesion)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.widgetCabecera = QtGui.QWidget(self.centralwidget)
        self.widgetCabecera.setGeometry(QtCore.QRect(0, 0, 800, 65))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widgetCabecera.setPalette(palette)
        self.widgetCabecera.setAutoFillBackground(True)
        self.widgetCabecera.setObjectName(_fromUtf8("widgetCabecera"))
        self.layoutWidget_2 = QtGui.QWidget(self.widgetCabecera)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 0, 162, 71))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.layoutWidget_2)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.labelColMedica = QtGui.QLabel(self.layoutWidget_2)
        self.labelColMedica.setStyleSheet(_fromUtf8("font: 30pt \"Ubuntu Condensed\";\n"
"color: rgb(255, 255, 255);"))
        self.labelColMedica.setObjectName(_fromUtf8("labelColMedica"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelColMedica)
        self.labelClinicManager = QtGui.QLabel(self.layoutWidget_2)
        self.labelClinicManager.setObjectName(_fromUtf8("labelClinicManager"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelClinicManager)
        self.widgetCuerpo = QtGui.QWidget(self.centralwidget)
        self.widgetCuerpo.setGeometry(QtCore.QRect(220, 110, 341, 271))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widgetCuerpo.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setBold(True)
        font.setWeight(75)
        self.widgetCuerpo.setFont(font)
        self.widgetCuerpo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.widgetCuerpo.setAutoFillBackground(True)
        self.widgetCuerpo.setObjectName(_fromUtf8("widgetCuerpo"))
        self.pushButtonIngresar = QtGui.QPushButton(self.widgetCuerpo)
        self.pushButtonIngresar.setGeometry(QtCore.QRect(230, 210, 89, 27))
        self.pushButtonIngresar.setObjectName(_fromUtf8("pushButtonIngresar"))
        self.widget_2 = QtGui.QWidget(self.widgetCuerpo)
        self.widget_2.setGeometry(QtCore.QRect(0, 10, 281, 51))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.labelIniciarSesion = QtGui.QLabel(self.widget_2)
        self.labelIniciarSesion.setGeometry(QtCore.QRect(20, -10, 211, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.labelIniciarSesion.setFont(font)
        self.labelIniciarSesion.setObjectName(_fromUtf8("labelIniciarSesion"))
        self.pushButtonOlvideLaContrasenia = QtGui.QPushButton(self.widgetCuerpo)
        self.pushButtonOlvideLaContrasenia.setGeometry(QtCore.QRect(70, 210, 151, 27))
        self.pushButtonOlvideLaContrasenia.setObjectName(_fromUtf8("pushButtonOlvideLaContrasenia"))
        self.widget = QtGui.QWidget(self.widgetCuerpo)
        self.widget.setGeometry(QtCore.QRect(20, 71, 301, 89))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.formLayout = QtGui.QFormLayout(self.widget)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.labelUsuario = QtGui.QLabel(self.widget)
        self.labelUsuario.setAutoFillBackground(False)
        self.labelUsuario.setObjectName(_fromUtf8("labelUsuario"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelUsuario)
        self.lineEditUsuario = QtGui.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditUsuario.setFont(font)
        self.lineEditUsuario.setObjectName(_fromUtf8("lineEditUsuario"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditUsuario)
        self.labelContrasenia = QtGui.QLabel(self.widget)
        self.labelContrasenia.setObjectName(_fromUtf8("labelContrasenia"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelContrasenia)
        self.lineEditContrasenia = QtGui.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditContrasenia.setFont(font)
        self.lineEditContrasenia.setObjectName(_fromUtf8("lineEditContrasenia"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditContrasenia)
        self.labelTipo = QtGui.QLabel(self.widget)
        self.labelTipo.setObjectName(_fromUtf8("labelTipo"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelTipo)
        self.comboBoxTipo = QtGui.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBoxTipo.setFont(font)
        self.comboBoxTipo.setObjectName(_fromUtf8("comboBoxTipo"))
        self.comboBoxTipo.addItem(_fromUtf8(""))
        self.comboBoxTipo.addItem(_fromUtf8(""))
        self.comboBoxTipo.addItem(_fromUtf8(""))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboBoxTipo)
        MainWindowIniciarSesion.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindowIniciarSesion)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindowIniciarSesion.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowIniciarSesion)
        QtCore.QMetaObject.connectSlotsByName(MainWindowIniciarSesion)

    def retranslateUi(self, MainWindowIniciarSesion):
        MainWindowIniciarSesion.setWindowTitle(_translate("MainWindowIniciarSesion", "Iniciar Sesion", None))
        self.labelColMedica.setText(_translate("MainWindowIniciarSesion", "ColMedica", None))
        self.labelClinicManager.setText(_translate("MainWindowIniciarSesion", "Clinic Manager", None))
        self.pushButtonIngresar.setText(_translate("MainWindowIniciarSesion", "Ingresar", None))
        self.labelIniciarSesion.setText(_translate("MainWindowIniciarSesion", "Iniciar Sesion", None))
        self.pushButtonOlvideLaContrasenia.setText(_translate("MainWindowIniciarSesion", "Olvide la contraseña", None))
        self.labelUsuario.setText(_translate("MainWindowIniciarSesion", "Usuario", None))
        self.labelContrasenia.setText(_translate("MainWindowIniciarSesion", "Contraseña", None))
        self.labelTipo.setText(_translate("MainWindowIniciarSesion", "Tipo", None))
        self.comboBoxTipo.setItemText(0, _translate("MainWindowIniciarSesion", "Administrador", None))
        self.comboBoxTipo.setItemText(1, _translate("MainWindowIniciarSesion", "Medico", None))
        self.comboBoxTipo.setItemText(2, _translate("MainWindowIniciarSesion", "Enfermera", None))

