from ControlDaoArea import ControlDaoArea

from ControlDaoPaciente import ControlDaoPaciente

from ControlDaosEmpleados import ControlDaosEmpleados
from ControlDaoMedico import ControlDaoMedico

from ControlDaoMedicamento import ControlDaoMedicamento