from ControlDaoArea import ControlDaoArea
from ControlDaoPaciente import ControlDaoPaciente
from ControlDaoHabilidades import ControlDaoHabilidades

from ControlDaosEmpleados import ControlDaosEmpleados
#from ControlDaosEmpleados import ControlDaoEnfermera
#from ControlDaosEmpleados import ControlDaoMedico

from ControlDaoMedicamento import ControlDaoMedicamento