from ControlDaoArea import ControlDaoArea

from ControlDaoPaciente import ControlDaoPaciente

from ControlDaosEmpleados import ControlDaosEmpleados

from ControlDaoCama import ControlDaoCama

from ControlDaoCamaPaciente import ControlDaoCamaPaciente

from ControlDaoHorarioMedico import ControlDaoHorarioMedico

from ControlDaoMedico import ControlDaoMedico

from ControlDaoCita import ControlDaoCita

from ControlDaoHistoriaClinica import ControlDaoHistoriaClinica

from ControlDaoLogin import ControlDaoLogin 
