# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowAdministrador.ui'
#
# Created: Sun Nov  9 17:07:02 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWindowAdministrador(object):
    def setupUi(self, mainWindowAdministrador):
        mainWindowAdministrador.setObjectName(_fromUtf8("mainWindowAdministrador"))
        mainWindowAdministrador.resize(800, 600)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        mainWindowAdministrador.setPalette(palette)
        mainWindowAdministrador.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        mainWindowAdministrador.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        mainWindowAdministrador.setAutoFillBackground(True)
        self.widgetPrincipal = QtGui.QWidget(mainWindowAdministrador)
        self.widgetPrincipal.setObjectName(_fromUtf8("widgetPrincipal"))
        self.widgetCabecera = QtGui.QWidget(self.widgetPrincipal)
        self.widgetCabecera.setGeometry(QtCore.QRect(0, 0, 800, 65))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 77, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widgetCabecera.setPalette(palette)
        self.widgetCabecera.setAutoFillBackground(True)
        self.widgetCabecera.setObjectName(_fromUtf8("widgetCabecera"))
        self.widgetUsuario = QtGui.QWidget(self.widgetCabecera)
        self.widgetUsuario.setGeometry(QtCore.QRect(590, 10, 41, 41))
        self.widgetUsuario.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.widgetUsuario.setAutoFillBackground(False)
        self.widgetUsuario.setStyleSheet(_fromUtf8("image: url(:/iconos/Admin.png);"))
        self.widgetUsuario.setObjectName(_fromUtf8("widgetUsuario"))
        self.layoutWidget = QtGui.QWidget(self.widgetCabecera)
        self.layoutWidget.setGeometry(QtCore.QRect(642, 10, 131, 46))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.layoutWidget)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.labelUsuario = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelUsuario.setFont(font)
        self.labelUsuario.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"font: 12pt \"Ubuntu Condensed\";"))
        self.labelUsuario.setObjectName(_fromUtf8("labelUsuario"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.labelUsuario)
        self.labelSalir = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelSalir.setFont(font)
        self.labelSalir.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"font: 12pt \"Ubuntu Condensed\";"))
        self.labelSalir.setObjectName(_fromUtf8("labelSalir"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.SpanningRole, self.labelSalir)
        self.layoutWidget1 = QtGui.QWidget(self.widgetCabecera)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 0, 162, 71))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.formLayout_2 = QtGui.QFormLayout(self.layoutWidget1)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.labelColMedica = QtGui.QLabel(self.layoutWidget1)
        self.labelColMedica.setStyleSheet(_fromUtf8("font: 30pt \"Ubuntu Condensed\";\n"
"color: rgb(255, 255, 255);"))
        self.labelColMedica.setObjectName(_fromUtf8("labelColMedica"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelColMedica)
        self.labelClinicManager = QtGui.QLabel(self.layoutWidget1)
        self.labelClinicManager.setObjectName(_fromUtf8("labelClinicManager"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelClinicManager)
        self.toolBoxHerramientas = QtGui.QToolBox(self.widgetPrincipal)
        self.toolBoxHerramientas.setGeometry(QtCore.QRect(0, 70, 200, 480))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.toolBoxHerramientas.setFont(font)
        self.toolBoxHerramientas.setObjectName(_fromUtf8("toolBoxHerramientas"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 200, 387))
        self.page.setObjectName(_fromUtf8("page"))
        self.commandLinkButtonNuevoEmpleado = QtGui.QCommandLinkButton(self.page)
        self.commandLinkButtonNuevoEmpleado.setGeometry(QtCore.QRect(10, 9, 181, 36))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.commandLinkButtonNuevoEmpleado.setFont(font)
        self.commandLinkButtonNuevoEmpleado.setObjectName(_fromUtf8("commandLinkButtonNuevoEmpleado"))
        self.commandLinkButtonModificarEmpleado = QtGui.QCommandLinkButton(self.page)
        self.commandLinkButtonModificarEmpleado.setGeometry(QtCore.QRect(10, 51, 181, 36))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.commandLinkButtonModificarEmpleado.setFont(font)
        self.commandLinkButtonModificarEmpleado.setObjectName(_fromUtf8("commandLinkButtonModificarEmpleado"))
        self.commandLinkButtonListarEmpleados = QtGui.QCommandLinkButton(self.page)
        self.commandLinkButtonListarEmpleados.setGeometry(QtCore.QRect(10, 93, 181, 36))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.commandLinkButtonListarEmpleados.setFont(font)
        self.commandLinkButtonListarEmpleados.setObjectName(_fromUtf8("commandLinkButtonListarEmpleados"))
        self.toolBoxHerramientas.addItem(self.page, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 200, 387))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.labelAreas = QtGui.QLabel(self.page_2)
        self.labelAreas.setGeometry(QtCore.QRect(10, 10, 58, 15))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setBold(True)
        font.setWeight(75)
        self.labelAreas.setFont(font)
        self.labelAreas.setObjectName(_fromUtf8("labelAreas"))
        self.labelCamas = QtGui.QLabel(self.page_2)
        self.labelCamas.setGeometry(QtCore.QRect(10, 160, 58, 15))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setBold(True)
        font.setWeight(75)
        self.labelCamas.setFont(font)
        self.labelCamas.setObjectName(_fromUtf8("labelCamas"))
        self.commandLinkButtonNuevaArea = QtGui.QCommandLinkButton(self.page_2)
        self.commandLinkButtonNuevaArea.setGeometry(QtCore.QRect(10, 30, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.commandLinkButtonNuevaArea.setFont(font)
        self.commandLinkButtonNuevaArea.setObjectName(_fromUtf8("commandLinkButtonNuevaArea"))
        self.commandLinkButtonModificarArea = QtGui.QCommandLinkButton(self.page_2)
        self.commandLinkButtonModificarArea.setGeometry(QtCore.QRect(10, 70, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.commandLinkButtonModificarArea.setFont(font)
        self.commandLinkButtonModificarArea.setObjectName(_fromUtf8("commandLinkButtonModificarArea"))
        self.commandLinkButtonListarAreas = QtGui.QCommandLinkButton(self.page_2)
        self.commandLinkButtonListarAreas.setGeometry(QtCore.QRect(10, 110, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.commandLinkButtonListarAreas.setFont(font)
        self.commandLinkButtonListarAreas.setObjectName(_fromUtf8("commandLinkButtonListarAreas"))
        self.commandLinkButtonListarCamas = QtGui.QCommandLinkButton(self.page_2)
        self.commandLinkButtonListarCamas.setGeometry(QtCore.QRect(10, 260, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.commandLinkButtonListarCamas.setFont(font)
        self.commandLinkButtonListarCamas.setObjectName(_fromUtf8("commandLinkButtonListarCamas"))
        self.commandLinkButtonNuevaCama = QtGui.QCommandLinkButton(self.page_2)
        self.commandLinkButtonNuevaCama.setGeometry(QtCore.QRect(10, 180, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.commandLinkButtonNuevaCama.setFont(font)
        self.commandLinkButtonNuevaCama.setObjectName(_fromUtf8("commandLinkButtonNuevaCama"))
        self.commandLinkButtonModificarCama = QtGui.QCommandLinkButton(self.page_2)
        self.commandLinkButtonModificarCama.setGeometry(QtCore.QRect(10, 220, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.commandLinkButtonModificarCama.setFont(font)
        self.commandLinkButtonModificarCama.setObjectName(_fromUtf8("commandLinkButtonModificarCama"))
        self.toolBoxHerramientas.addItem(self.page_2, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 200, 387))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.commandLinkButtonNuevoMedicamento = QtGui.QCommandLinkButton(self.page_3)
        self.commandLinkButtonNuevoMedicamento.setGeometry(QtCore.QRect(10, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.commandLinkButtonNuevoMedicamento.setFont(font)
        self.commandLinkButtonNuevoMedicamento.setObjectName(_fromUtf8("commandLinkButtonNuevoMedicamento"))
        self.commandLinkButtonModificarMedicamento = QtGui.QCommandLinkButton(self.page_3)
        self.commandLinkButtonModificarMedicamento.setGeometry(QtCore.QRect(10, 50, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.commandLinkButtonModificarMedicamento.setFont(font)
        self.commandLinkButtonModificarMedicamento.setObjectName(_fromUtf8("commandLinkButtonModificarMedicamento"))
        self.commandLinkButtonListarMedicamentos = QtGui.QCommandLinkButton(self.page_3)
        self.commandLinkButtonListarMedicamentos.setGeometry(QtCore.QRect(10, 90, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.commandLinkButtonListarMedicamentos.setFont(font)
        self.commandLinkButtonListarMedicamentos.setObjectName(_fromUtf8("commandLinkButtonListarMedicamentos"))
        self.toolBoxHerramientas.addItem(self.page_3, _fromUtf8(""))
        self.widgetCuerpo = QtGui.QWidget(self.widgetPrincipal)
        self.widgetCuerpo.setGeometry(QtCore.QRect(210, 70, 581, 481))
        self.widgetCuerpo.setObjectName(_fromUtf8("widgetCuerpo"))
        mainWindowAdministrador.setCentralWidget(self.widgetPrincipal)
        self.statusbar = QtGui.QStatusBar(mainWindowAdministrador)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        mainWindowAdministrador.setStatusBar(self.statusbar)
        self.actionNuevo_empleado = QtGui.QAction(mainWindowAdministrador)
        self.actionNuevo_empleado.setObjectName(_fromUtf8("actionNuevo_empleado"))
        self.actionListado_Empleados = QtGui.QAction(mainWindowAdministrador)
        self.actionListado_Empleados.setObjectName(_fromUtf8("actionListado_Empleados"))
        self.actionNueva_area = QtGui.QAction(mainWindowAdministrador)
        self.actionNueva_area.setObjectName(_fromUtf8("actionNueva_area"))
        self.actionListar_areas = QtGui.QAction(mainWindowAdministrador)
        self.actionListar_areas.setObjectName(_fromUtf8("actionListar_areas"))
        self.actionNueva_cama = QtGui.QAction(mainWindowAdministrador)
        self.actionNueva_cama.setObjectName(_fromUtf8("actionNueva_cama"))
        self.actionListar_camas = QtGui.QAction(mainWindowAdministrador)
        self.actionListar_camas.setObjectName(_fromUtf8("actionListar_camas"))
        self.actionNuevo_medicamento = QtGui.QAction(mainWindowAdministrador)
        self.actionNuevo_medicamento.setObjectName(_fromUtf8("actionNuevo_medicamento"))
        self.actionModificar_medicamento = QtGui.QAction(mainWindowAdministrador)
        self.actionModificar_medicamento.setObjectName(_fromUtf8("actionModificar_medicamento"))

        self.retranslateUi(mainWindowAdministrador)
        self.toolBoxHerramientas.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(mainWindowAdministrador)

    def retranslateUi(self, mainWindowAdministrador):
        mainWindowAdministrador.setWindowTitle(_translate("mainWindowAdministrador", "Administracion de Recursos", None))
        self.labelUsuario.setText(_translate("mainWindowAdministrador", "Usuario", None))
        self.labelSalir.setText(_translate("mainWindowAdministrador", "Salir", None))
        self.labelColMedica.setText(_translate("mainWindowAdministrador", "ColMedica", None))
        self.labelClinicManager.setText(_translate("mainWindowAdministrador", "Clinic Manager", None))
        self.commandLinkButtonNuevoEmpleado.setText(_translate("mainWindowAdministrador", "Nuevo Empleado", None))
        self.commandLinkButtonModificarEmpleado.setText(_translate("mainWindowAdministrador", "Modificar Empleado", None))
        self.commandLinkButtonListarEmpleados.setText(_translate("mainWindowAdministrador", "Listar Empleados", None))
        self.toolBoxHerramientas.setItemText(self.toolBoxHerramientas.indexOf(self.page), _translate("mainWindowAdministrador", "Personal", None))
        self.labelAreas.setText(_translate("mainWindowAdministrador", "Areas", None))
        self.labelCamas.setText(_translate("mainWindowAdministrador", "Camas", None))
        self.commandLinkButtonNuevaArea.setText(_translate("mainWindowAdministrador", "Nueva Area", None))
        self.commandLinkButtonModificarArea.setText(_translate("mainWindowAdministrador", "Modificar Area", None))
        self.commandLinkButtonListarAreas.setText(_translate("mainWindowAdministrador", "Listar Areas", None))
        self.commandLinkButtonListarCamas.setText(_translate("mainWindowAdministrador", "Listar Camas", None))
        self.commandLinkButtonNuevaCama.setText(_translate("mainWindowAdministrador", "Nueva Cama", None))
        self.commandLinkButtonModificarCama.setText(_translate("mainWindowAdministrador", "Modificar Cama", None))
        self.toolBoxHerramientas.setItemText(self.toolBoxHerramientas.indexOf(self.page_2), _translate("mainWindowAdministrador", "Infraestructura", None))
        self.commandLinkButtonNuevoMedicamento.setText(_translate("mainWindowAdministrador", "Nuevo Medicamento", None))
        self.commandLinkButtonModificarMedicamento.setText(_translate("mainWindowAdministrador", "Modificar Medicamento", None))
        self.commandLinkButtonListarMedicamentos.setText(_translate("mainWindowAdministrador", "Listar Medicamentos", None))
        self.toolBoxHerramientas.setItemText(self.toolBoxHerramientas.indexOf(self.page_3), _translate("mainWindowAdministrador", "Medicamentos", None))
        self.actionNuevo_empleado.setText(_translate("mainWindowAdministrador", "Nuevo empleado", None))
        self.actionListado_Empleados.setText(_translate("mainWindowAdministrador", "Modificar empleado", None))
        self.actionNueva_area.setText(_translate("mainWindowAdministrador", "Nueva area", None))
        self.actionListar_areas.setText(_translate("mainWindowAdministrador", "Listar areas", None))
        self.actionNueva_cama.setText(_translate("mainWindowAdministrador", "Nueva cama", None))
        self.actionListar_camas.setText(_translate("mainWindowAdministrador", "Listar camas", None))
        self.actionNuevo_medicamento.setText(_translate("mainWindowAdministrador", "Nuevo medicamento", None))
        self.actionModificar_medicamento.setText(_translate("mainWindowAdministrador", "Modificar medicamento", None))

import iconos.iconos_rc
