DROP TABLE IF EXISTS Area CASCADE;
DROP TABLE IF EXISTS Cama CASCADE;
DROP TABLE IF EXISTS Persona CASCADE;
DROP TABLE IF EXISTS Paciente CASCADE;
DROP TABLE IF EXISTS Empleado CASCADE;
DROP TABLE IF EXISTS Medico CASCADE;
DROP TABLE IF EXISTS Enfermera CASCADE;
DROP TABLE IF EXISTS Habilidad CASCADE;
DROP TABLE IF EXISTS Enfermera_Habilidad CASCADE;
DROP TABLE IF EXISTS Cama_Paciente CASCADE;
DROP TABLE IF EXISTS Historia_clinica CASCADE;
DROP TABLE IF EXISTS Horario_Consulta CASCADE;
DROP TABLE IF EXISTS Cita CASCADE;
DROP TABLE IF EXISTS Registro_Medico CASCADE;
DROP TABLE IF EXISTS Medicamento CASCADE;
DROP TABLE IF EXISTS Formula_Medica CASCADE;
DROP TABLE IF EXISTS Causa CASCADE;
DROP TABLE IF EXISTS Causa_Cita CASCADE;
DROP TABLE IF EXISTS Campana_Prevencion CASCADE;
DROP TABLE IF EXISTS Campana_Paciente CASCADE;


DROP SEQUENCE IF EXISTS seq_cod_area;
DROP SEQUENCE IF EXISTS seq_num_cama;
DROP SEQUENCE IF EXISTS seq_cod_habilidad;
DROP SEQUENCE IF EXISTS seq_num_historia;
DROP SEQUENCE IF EXISTSseq_id_horario;
DROP SEQUENCE IF EXISTS seq_num_registro;
DROP SEQUENCE IF EXISTS seq_cod_causa;